### ISSUE TITLE
Current Version 4.2 segfaults on MacOS Big Sur

### ISSUE THREAD

**Issue by tom111** [apaffenholz/homebrew-polymake#1]
Hi,

this is the install from `polymake-4.2.catalina.bottle.tar.gz` on MacOS Big Sur 11.0.1 on an Intel Mac:

> polymake
[1]    89664 segmentation fault  polymake

**Comment by apaffenholz** [comment]
Okay, that failed earlier than I expected and slightly ungraceful. But as the perl versions on Catalina and Big Sur differ that bottle can't work anyway, even if it would make it past the initial steps. The formula needs several changes for Big Sur, and maybe more than I expected. 

Yet, this will have to wait until I have access to something running with Big Sur.

**Comment by apaffenholz** [comment]
This should now be fixed for Intel Macs with Big Sur. Untested on Macs with arm processor.

**Comment by tom111** [comment]
Works on my Intel Mac. Thanks!
